[package]
name = "kouik"
version = "0.2.3"
authors = ["Ferry Jérémie <ferryjeremie@free.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="2.33"
nix = "0.23.1"
levenshtein = "1.0.5"
